version: 0.2

phases:
  install:
    commands:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 373127939256.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - ./mvnw package
      - docker build -t test-app:v1 .
      - docker tag test-app:v1 373127939256.dkr.ecr.us-west-2.amazonaws.com/test-app:v1
  post_build:
    commands:
      - docker push 373127939256.dkr.ecr.us-west-2.amazonaws.com/test-app:v1
